version: '3.8'

services: 
  movies_app: 
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - auth_service
      - movies_database
      - redis
    env_file:
      - docker.env
    ports: 
      - 8080:8080
  auth_service:
    build:
      context: .
      dockerfile: AuthServiceDockerfile
    env_file:
      - docker.env
    ports:
      - 3000:3000
  movies_database:
    image: mongo:4.4
    volumes:
      - movies_db:/data/db
    env_file:
      - docker.env
    restart: always
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data
    restart: always
    ports:
      - 6379:6379

volumes:
  movies_db:
  redis_data:
