/** This is just _loverFirst() of OmdbApiField */
export type RelevantField =
  | 'title'
  | 'year'
  | 'rated'
  | 'released'
  | 'runtime'
  | 'genre'
  | 'director'
  | 'writer'
  | 'actors'
  | 'plot'
  | 'language'
  | 'country'
  | 'awards'
  | 'poster'
  | 'ratings'
  | 'metascore'
  | 'imdbRating'
  | 'imdbVotes'
  | 'type'
  | 'dVD'
  | 'boxOffice'
  | 'production'
  | 'websiste';
